### create product
POST http://localhost:8080/erp/api/v1/products
Content-Type: application/json

{
  "name": "book",
  "price": 5.0
}

### get product by id
GET http://localhost:8080/erp/api/v1/products/1
Content-Type: application/json

### get products
GET http://localhost:8080/erp/api/v1/products
Content-Type: application/json

### udpate product
PUT http://localhost:8080/erp/api/v1/products/2
Content-Type: application/json

{
  "name": "phone",
  "price": 200.0
}

### delete product by id
DELETE http://localhost:8080/erp/api/v1/products/2
Content-Type: application/json

### get product by name
GET http://localhost:8080/erp/api/v1/products/name/sanjay%20shah
Content-Type: application/json
