server:
  port: 8080
  servlet:
    context-path: /erp
  compression:
    enabled: true
spring:
  main:
    allow-circular-references: true
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 3600
  application:
    name: nawatech-erp
  datasource:
    url: jdbc:mysql://localhost:3306/db_master
    username: root
    password: sanjuSP31@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  flyway:
    baseline-on-migrate: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 613676650425-mn9oafdlf2nmfsk6520ugeheukkpsnnh.apps.googleusercontent.com
            clientSecret: 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
            scope: email, profile, openid
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  mail:
    host: smtp.gmail.com
    port: 587
    username: messanjayshah31@gmail.com
    password: vipjglfkigsgkaib
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  thymeleaf:
    mode: HTML
    cache: false
support:
  email: messanjayshah31@gmail.com

#logging:
#  level:
#    org.springframework.security: DEBUG
audit:
  enabled: true
  api-enabled: true
  entity-change-enabled: true
